kind: Deployment
apiVersion: apps/v1
metadata:
  name: qod-api
  labels:
    app: qod-api
    tier: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qod-api
  template:
    metadata:
      labels:
        app: qod-api
    spec:
      containers:
        - name: qod-api
          image: ibmicpcoc/qod-api
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DB_HOST
              value: qod-db
            - name: DB_USER
              value: root
            - name: DB_PASS
              value: root
          imagePullPolicy: Always
      restartPolicy: Always
